### ISSUE TITLE
tool: setup prettier as precommit

### ISSUE THREAD

**Issue by nasreddineskandrani** [DMotivation/pf-01-react#29]
Setup precommit hooks via hisky running prettier.

**Comment by aminpaks** [comment]
What about editor/IDE integration. I find that a better option sometimes.

**Comment by nasreddineskandrani** [comment]
i didn't enable it but i ll do the 2.
The commit make sure all our code base has the same format and we will not see review comment about it anymore. I think the project reach a point where we need it :) which is a good newz.

**Comment by aminpaks** [comment]
Closed by #47 #48
